function plot_convergence_curves()
%PLOT_CONVERGENCE_CURVES Plot median convergence and interquartile bands.
% The script uses the available recorded trajectories in each MAT file.
% CEC 2014 D=30: F3, F10, F19, and F29; MaxFEs = 300,000.

    root_dir = fileparts(mfilename('fullpath'));
    output_dir = fullfile(root_dir, 'generated_figures');
    if ~exist(output_dir, 'dir')
        mkdir(output_dir);
    end

    functions = [3, 10, 19, 29];
    function_titles = { ...
        '(a) F3: Unimodal', ...
        '(b) F10: Simple multimodal', ...
        '(c) F19: Hybrid', ...
        '(d) F29: Composition'};
    checkpoint_pct = [1, 5, 10, 20, 50, 75, 100];
    max_fes = 300000;
    checkpoint_fes = round(checkpoint_pct / 100 * max_fes);
    error_floor = 1e-12;
    data_file_pattern = 'TF%d_cols50.mat';
    data_variable_name = 'data';

    algorithms = struct( ...
        'name', { ...
            'MAB-ABC', 'jSO', 'MadDE', 'LSHADE-SPACMA', ...
            'MPA', 'EO', 'BWO', 'ABCLIS', 'RNSABC', ...
            'BABC', 'ABC-AS^3'}, ...
        'folder', { ...
            'zong_ABC_MAB_c10_D30', 'zong_jSO_FEs_D30', 'madde', ...
            'zong_LSHADE_SPACMA_FEs_D30', 'mpa', 'EO', 'bwo', ...
            'ABC_LIS', 'ABC_RNS', 'ABC_B', 'zong_ABC_AS3_FEs_D30'}, ...
        'color', { ...
            [0.80, 0.10, 0.10], [0.00, 0.45, 0.74], [0.93, 0.49, 0.19], ...
            [0.20, 0.60, 0.25], [0.49, 0.18, 0.56], [0.00, 0.65, 0.65], ...
            [0.35, 0.35, 0.35], [0.30, 0.55, 0.90], [0.85, 0.33, 0.10], ...
            [0.47, 0.67, 0.19], [0.55, 0.35, 0.70]}, ...
        'line_style', { ...
            '-', '-', '--', '-.', ':', '--', '-.', '-', '--', '-.', ':'}, ...
        'marker', { ...
            'o', 's', '^', 'd', 'v', '>', '<', 's', '^', 'd', 'v'});

    nonabc_indices = [1, 2, 3, 4, 5, 6, 7];
    abc_indices = [1, 8, 9, 10, 11];

    draw_group_figure(root_dir, output_dir, algorithms, nonabc_indices, ...
        functions, function_titles, checkpoint_pct, checkpoint_fes, ...
        error_floor, data_file_pattern, data_variable_name, ...
        'convergence_nonabc_D30_cols50', ...
        'MAB-ABC and representative non-ABC algorithms');

    draw_group_figure(root_dir, output_dir, algorithms, abc_indices, ...
        functions, function_titles, checkpoint_pct, checkpoint_fes, ...
        error_floor, data_file_pattern, data_variable_name, ...
        'convergence_abc_D30_cols50', ...
        'MAB-ABC and ABC-family algorithms');

    fprintf('Convergence figures saved in: %s\n', output_dir);
end

function draw_group_figure(root_dir, output_dir, algorithms, group_indices, ...
    functions, function_titles, checkpoint_pct, checkpoint_fes, ...
    error_floor, data_file_pattern, data_variable_name, output_name, figure_name)

    figure_handle = figure('Color', 'w', 'Position', [80, 60, 1240, 860], ...
        'Name', figure_name, 'NumberTitle', 'off');

    axes_positions = [ ...
        0.075, 0.565, 0.405, 0.365; ...
        0.560, 0.565, 0.405, 0.365; ...
        0.075, 0.145, 0.405, 0.365; ...
        0.560, 0.145, 0.405, 0.365];

    line_handles = gobjects(numel(group_indices), 1);
    legend_labels = cell(numel(group_indices), 1);

    for function_index = 1:numel(functions)
        tf = functions(function_index);
        optimum = 100 * tf;
        axes_handle = axes('Parent', figure_handle, ...
            'Position', axes_positions(function_index, :)); %#ok<LAXES>
        hold(axes_handle, 'on');

        for local_index = 1:numel(group_indices)
            algorithm = algorithms(group_indices(local_index));
            input_file = fullfile(root_dir, algorithm.folder, ...
                sprintf(data_file_pattern, tf));
            assert(exist(input_file, 'file') == 2, ...
                'Missing convergence file: %s', input_file);

            loaded = load(input_file, data_variable_name);
            assert(isfield(loaded, data_variable_name), ...
                'Variable "%s" was not found in %s.', data_variable_name, input_file);
            trajectories = loaded.(data_variable_name);
            assert(size(trajectories, 1) >= max(checkpoint_fes), ...
                'Insufficient FE records in %s.', input_file);

            checkpoint_values = trajectories(checkpoint_fes, :);
            errors = max(checkpoint_values - optimum, error_floor);
            median_error = median(errors, 2);
            lower_quartile = row_percentile(errors, 25);
            upper_quartile = row_percentile(errors, 75);

            band_x = [checkpoint_pct, fliplr(checkpoint_pct)];
            band_y = [lower_quartile', fliplr(upper_quartile')];
            fill(axes_handle, band_x, band_y, algorithm.color, ...
                'FaceAlpha', 0.09, 'EdgeColor', 'none', ...
                'HandleVisibility', 'off');

            line_width = 1.45;
            marker_size = 4.5;
            if strcmp(algorithm.name, 'MAB-ABC')
                line_width = 2.4;
                marker_size = 6.0;
            end
            current_line = plot(axes_handle, checkpoint_pct, median_error, ...
                'Color', algorithm.color, ...
                'LineStyle', algorithm.line_style, ...
                'LineWidth', line_width, ...
                'Marker', algorithm.marker, ...
                'MarkerSize', marker_size, ...
                'MarkerFaceColor', 'w');

            if function_index == 1
                line_handles(local_index) = current_line;
                legend_labels{local_index} = sprintf('%s (n=%d)', ...
                    algorithm.name, size(trajectories, 2));
            end
        end

        set(axes_handle, 'YScale', 'log', 'FontName', 'Times New Roman', ...
            'FontSize', 10, 'LineWidth', 0.8, 'TickDir', 'out', ...
            'XTick', checkpoint_pct, 'XLim', [0, 101]);
        grid(axes_handle, 'on');
        axes_handle.GridAlpha = 0.18;
        axes_handle.MinorGridAlpha = 0.08;
        if function_index > 2
            xlabel(axes_handle, 'Evaluation budget used (%)', ...
                'FontName', 'Times New Roman', 'FontSize', 11);
        end
        ylabel(axes_handle, 'Best-so-far error (log scale)', ...
            'FontName', 'Times New Roman', 'FontSize', 11);
        title(axes_handle, function_titles{function_index}, ...
            'FontName', 'Times New Roman', 'FontSize', 12, ...
            'FontWeight', 'bold');
        box(axes_handle, 'on');
    end

    legend_handle = legend(line_handles, legend_labels, ...
        'Orientation', 'horizontal', 'Location', 'none', ...
        'FontName', 'Times New Roman', 'FontSize', 9, ...
        'Interpreter', 'tex', 'Box', 'off');
    legend_handle.NumColumns = min(numel(group_indices), 4);
    legend_handle.Position = [0.10, 0.018, 0.80, 0.080];

    png_file = fullfile(output_dir, [output_name, '.png']);
    eps_file = fullfile(output_dir, [output_name, '.eps']);
    print(figure_handle, png_file, '-dpng', '-r300');
    print(figure_handle, eps_file, '-depsc', '-painters');
    close(figure_handle);
end

function percentile_values = row_percentile(values, percentile)
% Toolbox-independent linear-interpolation percentile along each row.
    sorted_values = sort(values, 2);
    sample_count = size(sorted_values, 2);
    position = 1 + (sample_count - 1) * percentile / 100;
    lower_index = floor(position);
    upper_index = ceil(position);
    weight = position - lower_index;
    percentile_values = (1 - weight) .* sorted_values(:, lower_index) + ...
        weight .* sorted_values(:, upper_index);
end
